
= RISC-V Supervisor Binary Interface Specification

== Copyright and license information

This RISC-V SBI specification is

[%hardbreaks]
(C) 2019 Palmer Dabbelt <palmer@sifive.com>
(C) 2019 Atish Patra <atish.patra@wdc.com>

It is licensed under the Creative Commons Attribution 4.0 International
License (CC-BY 4.0).  The full license text is available at
https://creativecommons.org/licenses/by/4.0/.

== Introduction

This specification describes the RISC-V Supervisor Binary Interface, known from
here on as SBI.  This interface allows supervisor-mode software to be written
that is portable to all RISC-V implementations.  The design of the SBI follows
the general RISC-V philosophy of having a small core along with a set of
optional modular extensions.

=== Versioning and History

This document describes a draft of version 0.2 of the RISC-V SBI specification.

==== Changes Since Version 0.1

* The entire v0.1 SBI has been moved to the legacy extension, which is now an
  optional extension.  This is technically a backwards-incompatible change
  because the legacy extension is optional and v0.1 of the SBI doesn't allow
  probing, but it's as good as we can do.

== Binary Encoding

All SBI functions share a single binary encoding, which facilitates the mixing
of SBI extensions.  This binary encoding matches the standard RISC-V UNIX
syscall ABI, which itself is based on the calling convention defined in the
RISC-V ELF psABI.  In other words, SBI calls are exactly the same as standard
RISC-V function calls except that:

* An `ecall` is used as the control transfer instruction instead of a `call`
  instruction.
* `a7` (or `t0` on RV32E-based systems) encodes the SBI extension ID, which
  matches how the system call ID is encoded in the standard UNIX system call
  ABI.

Many SBI extensions also chose to encode an additional function ID in `a6`,
a scheme similar to the `ioctl()` system call on many UNIX operating systems.
This allows SBI extensions to encode multiple functions within the space of a
single extension.

In the name of compatibility, SBI extension IDs and SBI function IDs are
encoded as signed 32-bit integers.  When passed in registers these follow the
standard RISC-V calling convention rules.

SBI functions must return a pair of values in `a0` and `a1`, with `a0`
returning an error code.  This is analogous to returning the C structure

[source, C]
----
    struct sbiret {
        long error;
        long value;
    };
----

Standard SBI error codes are listed below

[cols="<,>",options="header,compact"]
|===
|  Error Type                |Value
|  SBI_SUCCESS               |  0
|  SBI_ERR_FAILED            | -1
|  SBI_ERR_NOT_SUPPORTED     | -2
|  SBI_ERR_INVALID_PARAM     | -3
|  SBI_ERR_DENIED            | -4
|  SBI_ERR_INVALID_ADDRESS   | -5
|  SBI_ERR_ALREADY_AVAILABLE | -6
|===

Every SBI function should prefer `unsigned long` as the data type. It keeps the
specification simple and easily adaptable for all RISC-V ISA types (i.e. RV32,
RV64 and RV128). In case the data is defined as 32bit wide, higher privilege
software must ensure that it only uses 32 bit data only.

If a SBI function needs to pass a list of harts to the higher privilege mode, it
must use a hart mask as defined below. This is applicable to any extensions defined
in or after v0.2.

Any function, requiring a hart mask, need to pass following two arguments.

* `unsigned long hart_mask` is a scalar bit-vector containing hartids
* `unsigned long hart_mask_base` is the starting hartid from which bit-vector
   must be computed.

In a single SBI function call, maximum number harts that can be set is always XLEN.
If a lower privilege mode needs to pass information about more than XLEN harts, it
should invoke multiple instances of the SBI function call. `hart_mask_base` can
be set to `-1` to indicate that `hart_mask` can be ignored and all available
harts must be considered.

Any function using hart mask may return following possible error value in addition
to function specific error values.

[cols="<,>",options="header,compact"]
|===
| Error code                | Description
| SBI_ERR_INVALID_PARAM     | Either `hart_mask_base` or any of the hartid from `hart_mask`
                              is not valid i.e. either the hartid is not enabled by the
			      platform or is not available to the supervisor.
|===

== SBI Base Functionality, Extension ID 0x10

The base of the supervisor binary interface is designed to be as small as
possible.  As such, it only contains functionality for probing which SBI
extensions are available and for querying the version of the SBI.  All
functions in the base must be supported by all SBI implementations, so there
are no error returns defined.

[source, C]
----
struct sbiret sbi_get_spec_version(void);
----
Returns the current SBI specification version.  This function must always
succeed.  The minor number of the SBI specification is encoded in the low 24
bits, with the major number encoded in the next 7 bits.  Bit 31 must be 0 and
is reserved for future expansion.

[source, C]
----
struct sbiret sbi_get_impl_id(void);
----
Returns the current SBI implementation ID, which is different for every SBI
implementation.  It is intended that this implementation ID allows software to
probe for SBI implementation quirks.

[source, C]
----
struct sbiret sbi_get_impl_version(void);
----
Returns the current SBI implementation version.  The encoding of this version
number is specific to the SBI implementation.

[source, C]
----
struct sbiret sbi_probe_extension(long extension_id);
----
Returns 0 if the given extension ID is not available, or an extension-specific
non-zero value if it is available.

[source, C]
----
struct sbiret sbi_get_mvendorid(void);
struct sbiret sbi_get_marchid(void);
struct sbiret sbi_get_mimpid(void);
----
Return a value that is legal for the corresponding CSR.  0 is always a legal
value for any of these CSRs.

=== Function Listing

[cols="<,,>",options="header,compact"]
|===
| Function Name                 | Function ID | Extension ID
| sbi_get_sbi_spec_version      |           0 |         0x10
| sbi_get_sbi_impl_id           |           1 |         0x10
| sbi_get_sbi_impl_version      |           2 |         0x10
| sbi_probe_extension           |           3 |         0x10
| sbi_get_mvendorid             |           4 |         0x10
| sbi_get_marchid               |           5 |         0x10
| sbi_get_mimpid                |           6 |         0x10
|===

=== SBI Implementation IDs

[cols="<,>",options="header,compact"]
|===
| Implementation ID | Name
| 0                 | Berkeley Boot Loader (BBL)
| 1                 | OpenSBI
| 2                 | Xvisor
| 3                 | KVM
|===

== Legacy SBI Extension, Extension IDs 0x00 through 0x0F

The legacy SBI extension ignores the function ID field,
instead being encoded as multiple
extension IDs.  Each of these extension IDs must be probed for directly.

The legacy SBI extension is deprecated in favor of the other extensions
listed below.
The legacy console SBI functions
(`sbi_console_getchar()` and `sbi_console_putchar ()`)
are expected to be deprecated; they have no replacement.

[source, C]
----
void sbi_set_timer(uint64_t stime_value)
----
Programs the clock for next event after *stime_value* time. This function also
clears the pending timer interrupt bit.

If the supervisor wishes to clear the timer interrupt without scheduling the next
timer event, it can either request a timer interrupt infinitely far into the
future (i.e., (uint64_t)-1), or it can instead mask the timer interrupt by
clearing sie.STIE.

[source, C]
----
void sbi_send_ipi(const unsigned long *hart_mask)
----
Send an inter-processor interrupt to all the harts defined in hart_mask.
Interprocessor interrupts manifest at the receiving harts as Supervisor Software
Interrupts.

hart_mask is a virtual address that points to a bit-vector of harts. The bit
vector is represented as a sequence of unsigned longs whose length equals the
number of harts in the system divided by the number of bits in an unsigned long,
rounded up to the next integer.

[source, C]
----
void sbi_clear_ipi(void)
----
Clears the pending IPIs if any. The IPI is cleared only in the hart for which
this SBI call is invoked.  `sbi_clear_ipi` is deprecated because S-mode code can
clear `sip.SSIP` directly.

[source, C]
----
void sbi_remote_fence_i(const unsigned long *hart_mask)
----
Instructs remote harts to execute FENCE.I instruction.
N.B. hart_mask is as described in sbi_send_ipi.

[source, C]
----
void sbi_remote_sfence_vma(const unsigned long *hart_mask,
                           unsigned long start,
                           unsigned long size)
----
Instructs the remote harts to execute one or more SFENCE.VMA instructions,
covering the range of virtual addresses between start and size.

[source, C]
----
void sbi_remote_sfence_vma_asid(const unsigned long *hart_mask,
                                unsigned long start,
                                unsigned long size,
                                unsigned long asid)
----
Instruct the remote harts to execute one or more SFENCE.VMA instructions,
covering the range of virtual addresses between start and size.  This covers
only the given ASID.

[source, C]
----
int sbi_console_getchar(void)
----
Read a byte from debug console; returns the byte on success, or -1 for failure.
Note. This is the only SBI call in the legacy extension that has a non-void
return type.

[source, C]
----
void sbi_console_putchar(int ch)
----
Write data present in *ch* to debug console.

Unlike `sbi_console_getchar`, this SBI call **will block** if there
remain any pending characters to be transmitted or if the receiving terminal
is not yet ready to receive the byte. However, if the console doesn't exist
at all, then the character is thrown away.

[source, C]
----
void sbi_shutdown(void)
----
Puts all the harts to shut down state from supervisor point of view. This SBI
call doesn't return.

=== Function Listing

[cols="<,,,>",options="header,compact"]
|===
| Function Name             | Function ID | Extension ID | Replacement Extension
| sbi_set_timer             |           0 |         0x00 |                   N/A
| sbi_console_putchar       |           0 |         0x01 |                   N/A
| sbi_console_getchar       |           0 |         0x02 |                   N/A
| sbi_clear_ipi             |           0 |         0x03 |                   N/A
| sbi_send_ipi              |           0 |         0x04 |                   N/A
| sbi_remote_fence_i        |           0 |         0x05 |                   N/A
| sbi_remote_sfence_vma     |           0 |         0x06 |                   N/A
| sbi_remote_sfence_vma_asid|           0 |         0x07 |                   N/A
| sbi_shutdown              |           0 |         0x08 |                   N/A
| *RESERVED*                |             |    0x09-0x0F |
|===


== Timer Extension, Extension ID: 0x54494D45 (TIME)
This replaces legacy timer extension (0x00). It follows the new calling convention
defined in v0.2.

[source, C]
----
struct sbiret sbi_set_timer(uint64_t stime_value)
----
Programs the clock for next event after *stime_value* time. *stime_value* is in absolute
time. This function must clear the pending timer interrupt bit as well.

If the supervisor wishes to clear the timer interrupt without scheduling the next
timer event, it can either request a timer interrupt infinitely far into the
future (i.e., (uint64_t)-1), or it can instead mask the timer interrupt by
clearing sie.STIE.

=== TIME Function Listing

[cols="<,,>",options="header,compact"]
|===
| Function Name                 | Function ID | Extension ID
| sbi_set_timer                 |           0 |   0x54494D45
|===


== IPI Extension, Extension ID: 0x735049 (sPI: s-mode IPI)
This extension replaces the legacy extension (0x04). The other IPI related
legacy extension(0x3) is deprecated now. All the functions in this extension
follow the `hart_mask` as defined in the binary encoding section.

[source, C]
----
struct sbiret sbi_send_ipi(unsigned long hart_mask, unsigned long hart_mask_base)
----
Send an inter-processor interrupt to all the harts defined in hart_mask.
Interprocessor interrupts manifest at the receiving harts as the supervisor software
interrupts.

*Returns* following possible values via sbiret.
[cols="<,>",options="header,compact"]
|===
| Error code                | Description
| SBI_SUCCESS               | IPI was sent to all the targeted harts successfully.
|===

=== IPI Function Listing

[cols="<,,>",options="header,compact"]
|===
| Function Name                 | Function ID | Extension ID
| sbi_send_ipi                  |           0 |     0x735049
|===

== RFENCE Extension, Extension ID: 0x52464E43 (RFNC)
This extension defines all remote fence related functions and replaces the
legacy extensions (0x05-0x07). All the functions follow the `hart_mask` as
defined in binary encoding section. Any function wishes to use range of
addresses (i.e. start_addr and size), have to abide by the below constraints
on range parameters.

The remote fence function acts as a full TLB flush if

	* `start_addr` and `size` are both 0
	* `size` is equal to 2^XLEN-1

[source, C]
----
struct sbiret sbi_remote_fence_i(unsigned long hart_mask, unsigned long hart_mask_base)
----
Instructs remote harts to execute FENCE.I instruction.

*Returns* following possible values via sbiret.
[cols="<,>",options="header,compact"]
|===
| Error code                | Description
| SBI_SUCCESS               | IPI was sent to all the targeted harts successfully.
|===

[source, C]
----
struct sbiret sbi_remote_sfence_vma(unsigned long hart_mask,
				    unsigned long hart_mask_base,
				    unsigned long start_addr,
				    unsigned long size)
----
Instructs the remote harts to execute one or more SFENCE.VMA instructions,
covering the range of virtual addresses between start and size.

*Returns* following possible values via sbiret.
[cols="<,>",options="header,compact"]
|===
| Error code                | Description
| SBI_SUCCESS               | IPI was sent to all the targeted harts successfully.
| SBI_ERR_INVALID_ADDRESS   | `start_addr` or `size` is not valid.
|===

[source, C]
----
struct sbiret sbi_remote_sfence_vma_asid(unsigned long hart_mask,
				unsigned long hart_mask_base,
                                unsigned long start_addr, unsigned long size,
                                unsigned long asid)
----
Instruct the remote harts to execute one or more SFENCE.VMA instructions,
covering the range of virtual addresses between start and size. This covers
only the given ASID.

*Returns* following possible values via sbiret.
[cols="<,>",options="header,compact"]
|===
| Error code                | Description
| SBI_SUCCESS               | IPI was sent to all the targeted harts successfully.
| SBI_ERR_INVALID_ADDRESS   | `start_addr` or `size` is not valid.
|===

[source, C]
----
struct sbiret sbi_remote_hfence_gvma_vmid(unsigned long hart_mask,
				unsigned long hart_mask_base,
                                unsigned long start_addr, unsigned long size,
                                unsigned long vmid)
----
Instruct the remote harts to execute one or more HFENCE.GVMA instructions,
covering the range of guest physical addresses between start and size only
for the given VMID. This function call is only valid for harts implementing
hypervisor extension.

*Returns* following possible values via sbiret.
[cols="<,>",options="header,compact"]
|===
| Error code                | Description
| SBI_SUCCESS               | IPI was sent to all the targeted harts successfully.
| SBI_ERR_NOT_SUPPORTED	    | This function is not supported as it is not implemented or
			      one of the target hart doesn't support hypervisor extension.
| SBI_ERR_INVALID_ADDRESS   | `start_addr` or `size` is not valid.
|===

[source, C]
----
struct sbiret sbi_remote_hfence_gvma(unsigned long hart_mask,
				unsigned long hart_mask_base,
                                unsigned long start_addr, unsigned long size)
----
Instruct the remote harts to execute one or more HFENCE.GVMA instructions,
covering the range of guest physical addresses between start and size for all
the guests. This function call is only valid for harts implementing hypervisor
extension.

*Returns* following possible values via sbiret.
[cols="<,>",options="header,compact"]
|===
| Error code                | Description
| SBI_SUCCESS               | IPI was sent to all the targeted harts successfully.
| SBI_ERR_NOT_SUPPORTED	    | This function is not supported as it is not implemented or
			      one of the target hart doesn't support hypervisor extension.
| SBI_ERR_INVALID_ADDRESS   | `start_addr` or `size` is not valid.
|===
 
[source, C]
----
struct sbiret sbi_remote_hfence_vvma_asid(unsigned long hart_mask,
				unsigned long hart_mask_base,
                                unsigned long start_addr, unsigned long size,
                                unsigned long asid)
----
Instruct the remote harts to execute one or more HFENCE.VVMA instructions,
covering the range of guest virtual addresses between start and size for the
given ASID and current VMID (in HGATP CSR) of calling hart. This function call
is only valid for harts implementing hypervisor extension.

*Returns* following possible values via sbiret.
[cols="<,>",options="header,compact"]
|===
| Error code                | Description
| SBI_SUCCESS               | IPI was sent to all the targeted harts successfully.
| SBI_ERR_NOT_SUPPORTED	    | This function is not supported as it is not implemented or
			      one of the target hart doesn't support hypervisor extension.
| SBI_ERR_INVALID_ADDRESS   | `start_addr` or `size` is not valid.
|===

[source, C]
----
struct sbiret sbi_remote_hfence_vvma(unsigned long hart_mask,
				unsigned long hart_mask_base,
                                unsigned long start_addr, unsigned long size)
----
Instruct the remote harts to execute one or more HFENCE.VVMA instructions,
covering the range of guest virtual addresses between start and size for
current VMID (in HGATP CSR) of calling hart. This function call is only valid
for harts implementing hypervisor extension.

*Returns* following possible values via sbiret.
[cols="<,>",options="header,compact"]
|===
| Error code                | Description
| SBI_SUCCESS               | IPI was sent to all the targeted harts successfully.
| SBI_ERR_NOT_SUPPORTED	    | This function is not supported as it is not implemented or
			      one of the target hart doesn't support hypervisor extension.
| SBI_ERR_INVALID_ADDRESS   | `start_addr` or `size` is not valid.
|===


=== RFENCE Function Listing

[cols="<,,>",options="header,compact"]
|===
| Function Name                 | Function ID | Extension ID
| sbi_remote_fence_i            |           0 |   0x52464E43
| sbi_remote_sfence_vma         |           1 |   0x52464E43
| sbi_remote_sfence_vma_asid    |           2 |   0x52464E43
| sbi_remote_hfence_gvma_vmid   |           3 |   0x52464E43
| sbi_remote_hfence_gvma   	|           4 |   0x52464E43
| sbi_remote_hfence_vvma_asid   |           5 |   0x52464E43
| sbi_remote_hfence_vvma   	|           6 |   0x52464E43
|===

== Hart State Management Extension, Extension ID: 0x48534D (HSM)

The Hart State Management Extension introduces a set of functions that allow the
supervisor to request higher privilege mode to start/stop harts running
in supervisor mode.

[source, C]
----
struct sbiret sbi_hart_start(unsigned long hartid, unsigned long start_addr, unsigned
long priv)
----

Informs the SBI implementation that the supervisor would like the given hart to
begin execution.  This call is asynchronous -- more specifically,
`sbi_hart_start()` may return before execution has actually begin as long as
the SBI implementation is capable of ensuring the return code is accurate.

*start_addr* points to a runtime-specified physical address, where a hart can
resume execution after its initialization/resume sequence.  Before jumping to
*start_addr*, the hart MUST configure PMP if present and switch to Supervisor
mode.

*priv* is an XLEN-bit value.  Upon execution from `start_addr`, `a1` will
contain this exact value.

*Returns* one of the following possible SBI error codes through sbiret.error.

[cols="<,>",options="header,compact"]
|===
| Error code                | Description
| SBI_SUCCESS               | Hart was previously in stopped state. It will start executing from `start_addr`.
| SBI_ERR_INVALID_ADDRESS   | `start_addr` is not valid possibly due to following reasons. +
                              * it is not a valid physical address. +
                              * The address is prohibited by PMP to run in supervisor mode +
| SBI_ERR_INVALID_PARAM     | `hartid` is not a valid hartid as corresponding hart cannot started in supervisor mode.
| SBI_ERR_ALREADY_AVAILABLE | The given hartid is already started.
| SBI_ERR_FAILED            | The start request failed for unknown reasons.
|===

The target hart jumps to higher privilege mode(S or VS mode) by executing at
`start_addr` with following values in specific registers.

[cols="<,>",options="header,compact"]
|===
|Register Name		|Value
|satp			|  0
|sstatus.sie		|  0
|a0			|hartid
|a1			|priv
|===

All other registers remain in an undefined state.

[source, C]
----
struct sbiret sbi_hart_stop()
----

Returns ownership of the calling hart back to the SBI implementation.  This
call is not expected to return under normal conditions.  `sbi_hart_stop()` must
be called with supervisor and user interrupts disabled.

*Returns* following SBI error code through sbiret.error only if it fails.

* SBI_ERR_FAILED

[source, C]
----
struct sbiret sbi_hart_status(unsigned long hartid)
----

*Returns* the current status of *hartid* in sbiret.value, or an error through
sbiret.error. The possible status values are shown on the table below.

[cols="<,,>",options="header,compact"]
|===
| Name                 		| Value | Description
| STARTED                     	|   0   | Already started
| STOPPED         		|   1   | Stopped
| START_REQUEST_PENDING       	|   2   | A start request pending
| STOP_REQUEST_PENDING       	|   3   | A stop request pending
|===

Possible error code:

* SBI_ERR_INVALID_PARAM: The given hartid is not valid

Since harts may transition state at any time due to any concurrent `sbi_hart_start` or
`sbi_hart_stop` calls, the return value from this function may not represent the actual
state of the hart at the time of return value verification.

=== HSM Function Listing

[cols="<,,>",options="header,compact"]
|===
| Function Name                 | Function ID | Extension ID
| sbi_hart_start      		|           0 |     0x48534D
| sbi_hart_stop           	|           1 |     0x48534D
| sbi_hart_get_status      	|           2 |     0x48534D
|===

== Performance Monitoring Unit Extension, Extension ID: 0x504D55 (PMU)

The RISC-V M-mode hardware performance counters such as MCYCLE, MINSTRET,
and MHPMCOUNTERx CSRs are accessible as read-only from S-mode and U-mode
using CYCLE, INSTRET, and HPMCOUNTERx CSRs. These performance counters can
only be started, stopped, or configured using MCOUNTINHIBIT and MHPMEVENTx
CSRs in M-mode.

A RISC-V implementation generally supports monitoring of various hardware
events using a limited number of hardware performance counters which are
up to 64 bits wide. In addition to the hardware performance counters, a SBI
implementation can provide software performance counters which can monitor
software events such as number of misaligned load/store instructions, number
of RFENCEs, number of IPIs, etc. The software counters are always XLEN bits
wide but not wider than 64 bits.

.The SBI PMU extension provides:
1. An interface for S-mode (or VS-mode) software to discover and configure
   per-HART hardware/software counters
2. A typical "perf" (https://en.wikipedia.org/wiki/Perf_(Linux)) compatible
   interface for hardware/software performance counters and events
3. Full access to microarchitecture's raw event encodings

To define SBI PMU extension calls, we first define important entities
`counter_idx`, `event_idx`, and `event_info`. The `counter_idx` is a
logical number assigned to each hardware/software counter. The `event_idx`
represents a hardware/software event whereas the `event_info` represents
additional configuration or parameters for the hardware/software event.

The event_idx is 20bits wide number encoded as follows:
[source, C]
----
    event_idx[19:16] = type
    event_idx[15:0] = code
----

=== Event: Hardware general events (Type #0)

The `event_idx.type` (i.e. *event type*) should be `0x0` for all hardware
general events and each hardware general event is identified by an unqiue
`event_idx.code` (i.e. *event code*) described in table below:

[cols="<,,>",options="header,compact"]
|===
| General Event Name                 | Event Code | Description
| SBI_PMU_HW_NO_EVENT                |          0 | Unused event because event_idx cannot be zero
| SBI_PMU_HW_CPU_CYCLES              |          1 | Event for each CPU cycle
| SBI_PMU_HW_INSTRUCTIONS            |          2 | Event for each completed instruction
| SBI_PMU_HW_CACHE_REFERENCES        |          3 | Event for cache hit
| SBI_PMU_HW_CACHE_MISSES            |          4 | Event for cache miss
| SBI_PMU_HW_BRANCH_INSTRUCTIONS     |          5 | Event for a branch instruction
| SBI_PMU_HW_BRANCH_MISSES           |          6 | Event for a branch misprediction
| SBI_PMU_HW_BUS_CYCLES              |          7 | Event for each BUS cycle
| SBI_PMU_HW_STALLED_CYCLES_FRONTEND |          8 | Event for a stalled cycle in microarchitecture frontend
| SBI_PMU_HW_STALLED_CYCLES_BACKEND  |          9 | Event for a stalled cycle in microarchitecture backend
| SBI_PMU_HW_REF_CPU_CYCLES          |         10 | Event for each reference CPU cycle
| SBI_PMU_HW_MISALIGNED_LOAD         |         11 | Event for misaligned load instruction
| SBI_PMU_HW_MISALIGNED_STORE        |         12 | Event for misaligned store instruction
|===

*NOTE:* the `event_info` (i.e. *event info*) is unused for hardware general
events and all non-zero values of `event_info` are reserved for future use.

=== Event: Hardware cache events (Type #1)

The `event_idx.type` (i.e. *event type*) should be `0x1` for all hardware
cache events and each hardware cache event is identified by an unqiue
`event_idx.code` (i.e. *event code*) which is encoded as follows:

[source, C]
----
    event_idx.code[15:3] = cache_id
    event_idx.code[2:1] = op_id
    event_idx.code[0:0] = result_id
----

Below tables show possible values of: `event_idx.code.cache_id` (i.e.
*cache event id*), `event_idx.code.op_id` (i.e. *cache operation id*)
and `event_idx.code.result_id` (i.e. *cache result id*).

[cols="<,,>",options="header,compact"]
|===
| Cache Event Name      | Cache Event ID | Description
| SBI_PMU_HW_CACHE_L1D  |              0 | Level1 data cache event
| SBI_PMU_HW_CACHE_L1I  |              1 | Level1 instruction cache event
| SBI_PMU_HW_CACHE_LL   |              2 | Last level cache event
| SBI_PMU_HW_CACHE_DTLB |              3 | Data TLB event
| SBI_PMU_HW_CACHE_ITLB |              4 | Instruction TLB event
| SBI_PMU_HW_CACHE_BPU  |              5 | Branch predictor unit event
| SBI_PMU_HW_CACHE_NODE |              6 | NUMA node cache event
|===

[cols="<,,>",options="header,compact"]
|===
| Cache Operation Name         | Cache Operation ID | Description
| SBI_PMU_HW_CACHE_OP_READ     |                  0 | Read cache line
| SBI_PMU_HW_CACHE_OP_WRITE    |                  1 | Write cache line
| SBI_PMU_HW_CACHE_OP_PREFETCH |                  2 | Prefetch cache line
|===

[cols="<,,>",options="header,compact"]
|===
| Cache Result Name              | Cache Result ID | Description
| SBI_PMU_HW_CACHE_RESULT_ACCESS |               0 | Cache access
| SBI_PMU_HW_CACHE_RESULT_MISS   |               1 | Cache miss
|===

*NOTE:* the `event_info` (i.e. *event info*) is unused for hardware cache
events and all non-zero values of `event_info` are reserved for future use.

=== Event: Hardware raw events (Type #2)

The `event_idx.type` (i.e. *event type*) should be `0x2` for all hardware
raw events and `event_idx.code` (i.e. *event code*) should be zero. The
`event_info` parameter of `sbi_pmu_counter_config_matching()` call (described
below) should have the non-zero raw event value to be programmed in the
MHPMEVENTx CSR.

=== Event: Software events (Type #15)

The `event_idx.type` (i.e. *event type*) should be `0xf` for all software
events and each software event is identified by an unqiue `event_idx.code`
(i.e. *event code*) described in table below:

[cols="<,,>",options="header,compact"]
|===
| Software Event Name                  | Event Code | Description
| SBI_PMU_SW_MISALIGNED_LOAD           |          0 | Misaligned load trap event
| SBI_PMU_SW_MISALIGNED_STORE          |          1 | Misaligned store trap event
| SBI_PMU_SW_ACCESS_LOAD               |          2 | Load access trap event
| SBI_PMU_SW_ACCESS_STORE              |          3 | Store access trap event
| SBI_PMU_SW_ILLEGAL_INSN              |          4 | Illegal instruction trap event
| SBI_PMU_SW_SET_TIMER                 |          5 | Set timer event
| SBI_PMU_SW_IPI_SENT                  |          6 | Sent IPI to other HART event
| SBI_PMU_SW_IPI_RECEIVED              |          7 | Received IPI from other HART event
| SBI_PMU_SW_FENCE_I_SENT              |          8 | Sent FENCE.I request to other HART event
| SBI_PMU_SW_FENCE_I_RECEIVED          |          9 | Received FENCE.I request from other HART event
| SBI_PMU_SW_SFENCE_VMA_SENT           |         10 | Sent SFENCE.VMA request to other HART event
| SBI_PMU_SW_SFENCE_VMA_RECEIVED       |         11 | Received SFENCE.VMA request from other HART event
| SBI_PMU_SW_SFENCE_VMA_ASID_SENT      |         12 | Sent SFENCE.VMA with ASID request to other HART event
| SBI_PMU_SW_SFENCE_VMA_ASID_RECEIVED  |         13 | Received SFENCE.VMA with ASID request from other HART event
| SBI_PMU_SW_HFENCE_GVMA_SENT          |         14 | Sent HFENCE.GVMA request to other HART event
| SBI_PMU_SW_HFENCE_GVMA_RECEIVED      |         15 | Received HFENCE.GVMA request from other HART event
| SBI_PMU_SW_HFENCE_GVMA_VMID_SENT     |         16 | Sent HFENCE.GVMA with VMID request to other HART event
| SBI_PMU_SW_HFENCE_GVMA_VMID_RECEIVED |         17 | Received HFENCE.GVMA with VMID request from other HART event
| SBI_PMU_SW_HFENCE_VVMA_SENT          |         18 | Sent HFENCE.VVMA request to other HART event
| SBI_PMU_SW_HFENCE_VVMA_RECEIVED      |         19 | Received HFENCE.VVMA request from other HART event
| SBI_PMU_SW_HFENCE_VVMA_ASID_SENT     |         20 | Sent HFENCE.VVMA with ASID request to other HART event
| SBI_PMU_SW_HFENCE_VVMA_ASID_RECEIVED |         21 | Received HFENCE.VVMA with ASID request from other HART event
|===

*NOTE:* the `event_info` (i.e. *event info*) is unused for software events
and all non-zero values of `event_info` are reserved for future use.

=== Function: Get number of counters (ID #0)

[source, C]
----
struct sbiret sbi_pmu_num_counters()
----

*Returns* the number of counters (both hardware and software) in sbiret.value
and always returns `SBI_SUCCESS` in sbiret.error.

=== Function: Get details of a counter (ID #1)

[source, C]
----
struct sbiret sbi_pmu_counter_get_info(unsigned long counter_idx)
----

Get details about the specified counter such as underlying CSR number,
width of the counter, type of counter hardware/software, etc.

The `counter_info` returned by this SBI call is encoded as follows:
[source, C]
----
    counter_info[11:0] = CSR (12bit CSR number)
    counter_info[17:12] = Width (One less than number of bits in CSR)
    counter_info[XLEN-2:18] = Reserved for future use
    counter_info[XLEN-1] = Type (0 = hardware and 1 = software)
----

If `counter_info.type == 0x1` then `counter_info.csr` and `counter_info.width`
should be ignored.

*Returns* the `counter_info` described above in sbiret.value and returns
one of the following possible SBI error codes in sbiret.error.
[cols="<,>",options="header,compact"]
|===
| Error code                | Description
| SBI_SUCCESS               | `counter_info` read successfully.
| SBI_ERR_INVALID_PARAM     | `counter_idx` points to an invalid counter.
|===

=== Function: Find and configure a matching counter (ID #2)

[source, C]
----
struct sbiret sbi_pmu_counter_config_matching(unsigned long counter_idx_base,
					      unsigned long counter_idx_mask,
					      unsigned long event_idx,
					      unsigned long event_info)
----

Find and configure a counter from a set of counters which is not started
(or enabled) and can monitor the specified event. The `counter_idx_base`
and `counter_idx_mask` parameters represent the set of counters whereas
the `event_idx` and `event_info` represent the event to be monitored.

*Returns* the `counter_idx` in sbiret.value upon success and returns one
of the following possible SBI error codes in sbiret.error.
[cols="<,>",options="header,compact"]
|===
| Error code                | Description
| SBI_SUCCESS               | counter found and configured successfully.
| SBI_ERR_INVALID_PARAM     | set of counters has an invalid counter.
| SBI_ERR_NOT_SUPPORTED     | None of the counters can monitor specified event.
|===

=== Function: Read a software counter (ID #3)

[source, C]
----
struct sbiret sbi_pmu_counter_soft_read(unsigned long counter_idx)
----

Provide the current value of a software counter.

*Returns* the software counter value in sbiret.value and returns one of the
following possible SBI error codes in sbiret.error.
[cols="<,>",options="header,compact"]
|===
| Error code                | Description
| SBI_SUCCESS               | software counter read successfully.
| SBI_ERR_INVALID_PARAM     | `counter_idx` points to a hardware counter or an invalid counter.
|===

=== Function: Start a counter (ID #4)

[source, C]
----
struct sbiret sbi_pmu_counter_start(unsigned long counter_idx, uint64_t initial_value)
----

Start or enable the specified counter on the calling HART with the specified
initial value.

*Returns* one of the following possible SBI error codes in sbiret.error.
[cols="<,>",options="header,compact"]
|===
| Error code                | Description
| SBI_SUCCESS               | counter started successfully.
| SBI_ERR_INVALID_PARAM     | `counter_idx` points to an invalid counter.
| SBI_ERR_ALREADY_AVAILABLE | counter already started.
|===

=== Function: Stop a counter (ID #5)

[source, C]
----
struct sbiret sbi_pmu_counter_stop(unsigned long counter_idx)
----

Stop or disable the specified counter on the calling HART.

*Returns* one of the following possible SBI error codes in sbiret.error.
[cols="<,>",options="header,compact"]
|===
| Error code                | Description
| SBI_SUCCESS               | counter stopped successfully.
| SBI_ERR_INVALID_PARAM     | `counter_idx` points to an invalid counter.
| SBI_ERR_ALREADY_AVAILABLE | counter already stopped.
|===

=== Function Listing

[cols="<,,>",options="header,compact"]
|===
| Function Name                   | Function ID | Extension ID
| sbi_pmu_num_counters            |           0 |     0x504D55
| sbi_pmu_counter_get_info        |           1 |     0x504D55
| sbi_pmu_counter_config_matching |           2 |     0x504D55
| sbi_pmu_counter_soft_read       |           3 |     0x504D55
| sbi_pmu_counter_start           |           4 |     0x504D55
| sbi_pmu_counter_stop            |           5 |     0x504D55
|===

== Experimental SBI Extension Space, Extension IDs 0x08000000 through 0x08FFFFFF

No management.

== Vendor-Specific SBI Extension Space, Extension Ids 0x09000000 through 0x09FFFFFF

Low bits from `mvendorid`.

== Firmware Code Base Specific SBI Extension Space, Extension Ids 0x0A000000 through 0x0AFFFFFF

Low bits is SBI implementation ID. The firmware code base SBI extension is the additional 
SBI extensions to SBI implementation. That provides the firmware code base specific SBI functions
which are defined in the external firmware specification.

